### ISSUE TITLE
Issue with LED rpyc

### ISSUE THREAD

**Issue by petorian** [x821938/PoorMansBashBunny#2]
The LEDS of the board won't blink. I did a fresh install, following the guide. (using Raspberry Stretch Lite).
When running the bunny-launcher I see it has trouble 
```
./bunny-launcher.py`
INFO:root:IO setup completed
INFO:root:DIP Switch : 0
INFO:root:Launching boot script at: /bunny/payloads/0/boot
Traceback (most recent call last):
  File "./bunny-launcher.py", line 142, in <module>
    t = ThreadedServer(ledService, port=TCP_PORT)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 89, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/bin/LED", line 13, in <module>
    c.root.blink(led, mode)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 501, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/async_.py", line 95, in value
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/async_.py", line 45, in wait
    self._conn.serve(self._ttl)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 387, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 50, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 230, in read
    raise EOFError("connection closed by peer")
EOFError: connection closed by peer
Traceback (most recent call last):
  File "/usr/bin/LED", line 13, in <module>
    c.root.blink(led, mode)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 501, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/async_.py", line 95, in value
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/async_.py", line 45, in wait
    self._conn.serve(self._ttl)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 387, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 50, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 230, in read
    raise EOFError("connection closed by peer")
EOFError: connection closed by peer

```

**Comment by petorian** [comment]
Log from syslog:
```
Jun 12 11:00:47 raspberrypi systemd[1]: Started bunny-launcher.service.
Jun 12 11:00:53 raspberrypi node-pibunny[252]: INFO:root:IO setup completed
Jun 12 11:00:53 raspberrypi node-pibunny[252]: INFO:root:DIP Switch : 0
Jun 12 11:00:53 raspberrypi node-pibunny[252]: INFO:root:Launching boot script at: /bunny/payloads/0/boot
Jun 12 11:00:53 raspberrypi node-pibunny[252]: INFO:LED/18861:server started on [0.0.0.0]:18861
Jun 12 11:00:54 raspberrypi node-pibunny[252]: INFO:LED/18861:accepted ('127.0.0.1', 56790) with fd 5
Jun 12 11:00:55 raspberrypi node-pibunny[252]: INFO:LED/18861:welcome ('127.0.0.1', 56790)
Jun 12 11:00:55 raspberrypi node-pibunny[252]: INFO:LED/18861:goodbye ('127.0.0.1', 56790)
Jun 12 11:00:55 raspberrypi node-pibunny[252]: ERROR:LED/18861:client connection terminated abruptly
Jun 12 11:00:55 raspberrypi node-pibunny[252]: Traceback (most recent call last):
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 181, in _authenticate_and_serve_client
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self._serve_client(sock2, credentials)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 202, in _serve_client
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     conn = self.service._connect(Channel(SocketStream(sock)), config)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/service.py", line 100, in _connect
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self.on_connect(conn)
Jun 12 11:00:55 raspberrypi node-pibunny[252]: TypeError: on_connect() takes exactly 1 argument (2 given)
Jun 12 11:00:55 raspberrypi node-pibunny[252]: Traceback (most recent call last):
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/bin/LED", line 13, in <module>
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     c.root.blink(led, mode)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 501, in root
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 471, in sync_request
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     return self.async_request(handler, *args, timeout=timeout).value
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/async_.py", line 95, in value
Jun 12 11:00:55 raspberrypi node-pibunny[252]: Exception in thread Thread-2:
Jun 12 11:00:55 raspberrypi node-pibunny[252]: Traceback (most recent call last):
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self.run()
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self.__target(*self.__args, **self.__kwargs)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 181, in _authenticate_and_serve_client
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self._serve_client(sock2, credentials)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 202, in _serve_client
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     conn = self.service._connect(Channel(SocketStream(sock)), config)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/service.py", line 100, in _connect
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self.on_connect(conn)
Jun 12 11:00:55 raspberrypi node-pibunny[252]: TypeError: on_connect() takes exactly 1 argument (2 given)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self.wait()
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/async_.py", line 45, in wait
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     self._conn.serve(self._ttl)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 387, in serve
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     data = self._channel.poll(timeout) and self._channel.recv()
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 50, in recv
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     header = self.stream.read(self.FRAME_HEADER.size)
Jun 12 11:00:55 raspberrypi node-pibunny[252]:   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 230, in read
Jun 12 11:00:55 raspberrypi node-pibunny[252]:     raise EOFError("connection closed by peer")
Jun 12 11:00:55 raspberrypi node-pibunny[252]: EOFError: connection closed by peer
```

**Comment by x821938** [comment]
It seemed like rpyc was updated since I wrote it... It should be corrected now.

**Comment by petorian** [comment]
Works
